version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: sodner_db
    environment:
      - POSTGRES_USER=sodner_santiago
      - POSTGRES_PASSWORD=passw0rdSantiago
      - POSTGRES_DB=sodner
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local